// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnyttbkbmvjwvauhzjtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRueXR0YmtibXZqd3ZhdWh6anRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDE3MTIsImV4cCI6MjA1OTY3NzcxMn0.j6-SrRZQUQEGzeYQq-2tOLLxAKK8-nXPmeQn3q0eR9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);